- app/controllers/manage/finishers_controller.rb
- app/views/manage/finishers/_finisher.html.haml
- app/views/manage/finishers/_finisher_card.html.haml
- app/views/manage/finishers/card.html.haml
- app/views/manage/finishers/map.html.haml
- config/routes.rb
This pr adds a finisher card view to the map info window displayed when a user selects a pin on a map.  It also adds a table under the map instead of a card listing of finishers.
- Created a card partial
- Created a `manage/finishers/{finisher_id}/card` route to be used by map js to display info window
- Moved info window instantiation out side of for loop that was preventing auto closure and multiple server requests in new generation.
> Enhance manage/finishers/map

- app/views/manage/finishers/_finisher_card.html.haml
Image styling tweak for card. 
OLD:
NEW:
> adjust css for image in card

- app/views/manage/finishers/show.html.haml
- when clicking on a the finisher photo it opens the full resolution photo in a new tab
- added some styling tweaks to first column to make spacing and bold font consistent
> Make finishers headshots higher resolution [sc-17]

- app/assets/stylesheets/application.sass
- app/views/devise/registrations/new.html.haml
- app/views/finishers/_favorites_form.html.haml
- app/views/finishers/_profile_form.html.haml
- app/views/finishers/_skills_form.html.haml
- app/views/layouts/_address_form.html.haml
> Can we put optional next to optional questions [sc-41]

- app/views/manage/finishers/_search.html.haml
Adds the new sorted_by_popularity and order(:name) to Skill and Product drop downs
> Sort Skill and Product dropdowns

- app/controllers/manage/finishers_controller.rb
- app/models/finisher.rb
- app/views/manage/finishers/map.html.haml
This adds a radius drop down so Masey can expand the search if needed.  Defaults to 50 (miles)
> Adding a radius drop down to the map

- app/controllers/admin/users_controller.rb
- app/controllers/manage/projects_controller.rb
- app/models/project.rb
- app/models/user.rb
- app/views/admin/users/_form.html.haml
- app/views/admin/users/show.html.haml
- app/views/manage/projects/_form.html.haml
- app/views/manage/projects/index.html.haml
- app/views/manage/projects/show.html.haml
- db/migrate/20240326024112_add_manager_to_projects.rb
- db/schema.rb
This adds Project Managers to projects
Adding manager_id foreign key, exposing as `belongs_to :manager` (a User) in project
Adding is_project_manager boolean to User
Enabled editing these fields on the Project and User, respectively.
Allowing for filtering in the Project search, to return projects managed by a particular user.  We can make custom dashboard views per manager.
> Adding project managers to projects

- db/migrate/20230108181958_create_volunteers.rb
- db/migrate/20230108182812_create_assignments.rb
- db/migrate/20230108184735_create_assessments.rb
- db/migrate/20230816225430_add_joined_on_to_volunteers.rb
I'm not sure if this PR is still required. Please advise!
The goal of the PR was to restore the migration files to preserve the term `volunteers` in all files before `20230910220917_change_volunteers_to_finishers.rb`. Since the migration files had been edited to replace `volunteers` with `finishers`, it wasn't possible to run the migrations after a fresh `db:create`. However, if new dev environments should be set up using `db:schema:load`, this PR isn't necessary because `db:schema:load` works just fine without these changes. I would only push to merge this change if there's a case for needing to be able to run `db:migrate`.
Here are some snapshots of the DB tables after the changes in this PR, showing that everything resolves to reference `finishers` instead of `volunteers`:
> Restore volunteers in migration files before change to finishers

- app/models/finisher.rb
- app/views/manage/finishers/_search.html.haml
Adds a filter for "Employer Match" to the /manage/finishers search view.
Not filtered by "Employer Match" (there are 3 finishers in my DB):
Filtered by "Employer Match" (there are 2 finishers in my DB with has_workplace_match set to true):
> Add filter to finisher search for has workplace match

- app/controllers/manage/projects_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/toggle_ready_status.js
- app/javascript/controllers/toggle_status_controller.js
- app/models/project.rb
- app/views/manage/dashboards/show.html.haml
- app/views/manage/projects/_form.html.haml
- app/views/manage/projects/index.html.haml
- app/views/manage/projects/show.html.haml
- db/migrate/20241103112120_add_ready_status_to_projects.rb
- db/migrate/20241104104032_add_in_process_status_to_projects.rb
- db/schema.rb
This PR adds all the newly-aligned project statuses to the web app. I elected to add the whole list of statuses as project statuses (rather than having some as assignee statuses) to mimic what is done in Google Sheets currently. This will make searching and the workflow in general more like the way it is currently done.
Both `Ready to Match` and `In Process` have five statuses of their own. These options are shown conditionally when `Ready to Match` or `In Process` is selected in the status dropdown. The new dropdowns have been added to the manage projects dashboard and the edit project page (I think those are the only two places they need to be).
[Screen Recording 2024-11-04 at 7.35.46 AM.mov.zip](https://github.com/user-attachments/files/17617234/Screen.Recording.2024-11-04.at.7.35.46.AM …
> Add new statuses to projects

- db/migrate/20241111235510_set_new_default_project_status.rb
- db/schema.rb
I just tried adding a new project after the recent changes to add the new project statuses to the app. With the change from 'draft' status to 'drafted' status, the default that gets set upon creating a new project was not updated. This PR adds the migration to change the default so new projects can successfully be created again.
> Add migration to default new project statuses to drafted

- app/views/manage/projects/_form.html.haml
- app/views/manage/projects/index.html.haml
- app/views/manage/projects/show.html.haml
Updates the locations where we humanize the in process statuses to convert any instance of 'po' or 'Po' to 'PO'. It still saves in the DB as a lowercase string as it should.
> Use regex to capitalize PO in project in process statuses

- app/views/projects/show.html.haml
When editing the `More` section in a new project, the user should be taken to the first page of the project submission flow (:edit_basics).
https://github.com/user-attachments/assets/5a95ba4d-765b-46cc-b6c4-d3780c44fd1b
> Fix link to edit more in projects

- app/views/manage/projects/_form.html.haml
- app/views/projects/_crafter_form.html.haml
- app/views/projects/_project_form.html.haml
A couple of small copy fixes for the project submission form and manage projects. Updated the question about cigarette smoke in the home and type of project material. Also changed the column width for "Is there a pattern" so it no longer wraps onto a second line.
Slack list items:
* https://looseendsproject.slack.com/lists/T05GP1TRWQM/F079DEBF90W?record_id=Rec07H8A509RT
* https://looseendsproject.slack.com/lists/T05GP1TRWQM/F079DEBF90W?record_id=Rec07HB3S55AP
Material Details:
Crafter Details:
Is there a pattern column width:
> Update text about material and cigarette smoke for projects

- app/controllers/manage/projects_controller.rb
- app/views/manage/projects/index.html.haml
The new project attribute checkbox fields need to be searchable. This PR adds the ability to search for projects on the /manage/projects page according to whether any of the checkboxes are checked.
https://github.com/user-attachments/assets/6619e1c6-013d-4e30-b80c-0a59d5be2bca
> Make project attribute checkboxes searchable

- app/controllers/manage/projects_controller.rb
- app/controllers/projects_controller.rb
- app/views/projects/_basics_form.html.haml
- app/views/projects/new.html.haml
- app/views/projects/show.html.haml
- db/migrate/20250114103453_add_can_use_first_name_to_projects.rb
- db/schema.rb
This PR updates text and adds a new field to the projects controller (can_use_first_name), as required by this List item: https://looseendsproject.slack.com/lists/T05GP1TRWQM/F079DEBF90W?record_id=Rec07H89HB7NH
> Update text for project submissions

- app/views/projects/show.html.haml
Updates the "unfinished" text on the projects show page.
Periods were added after:
* Tell us about the material
* Tell us about the pattern
* We'd love to know more about the crafter
And "We'd love to know more about the crafter" was given the text-danger class because there are required fields that need to be filled out.
Links to Slack list items:
* https://looseendsproject.slack.com/lists/T05GP1TRWQM/F079DEBF90W?record_id=Rec07HDLTPCDA
* https://looseendsproject.slack.com/lists/T05GP1TRWQM/F079DEBF90W?record_id=Rec07HB6JKGJW
Before:
After:
> Make Projects unfinished text red and add periods

- config/routes.rb
Handle GET requests to /users by redirecting back to /users/sign_up. The site would respond "no route matches [GET] '/users'" if a user used the browser refresh _after_ submitting a sign up with invalid data. After this change, the user will be redirected back to the sign up page to continue.
See Also: [Slack list item](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F079DEBF90W?record_id=Rec08AXLAQMNH)
> Handle GET requests to /users

- app/views/manage/projects/_form.html.haml
- config/routes.rb
This change moves the search action from /manage/projects/:project_id/finishers/search(.:format) to /manage/projects/finishers/search(.:format) as the :project_id was not used in the search action.
The finisher autocomplete route was set to require a :project_id. When creating a new project the path method was being called with a valid Project object, but one which had no id (from Project.new). This caused the path method to raise an error because it was trying to use the id of the Project object as the :project_id parameter. Since the project id was not used by the search it seemed easiest to remove the requirement for the :project_id parameter.
It's not totally clear to me how #48 uncovered this as it was focused on moving the existing HAML structure around and should not have changed …
> Remove project_id requirements for finisher autocomplete.

- app/views/devise/registrations/new.html.haml
While testing #50, I realized a couple other of our form inputs weren't screen reader accessible. It's a quick fix, so I wanted to get it up.
Added the specific attribute to the FormBuilder's label method so the input is correctly labeled for screen readers.
[Docs about FormBuilder and the label method](https://api.rubyonrails.org/v8.0.1/classes/ActionView/Helpers/FormBuilder.html#method-i-label)
> Make inputs on sign up screen reader accessible

- .gitignore
1. Did `heroku pg:backups:schedule` for 2am daily America/New_York.  Seven day retention
2. Downloaded manual backup and restored to dev db
3. Updated .gitignore so backups won't get committed (as long as you put them in /db/backups)
> capture pgdump from prod periodically

- app/controllers/manage/finishers_controller.rb
- app/controllers/manage/projects_controller.rb
- config/initializers/geocoder.rb
- test/controllers/manage/finishers_controller_test.rb
- test/controllers/manage/projects_controller_test.rb
- test/test_helper.rb
Add some smoke tests for the project manage controller actions. This would have caught the bug in https://github.com/looseendsproject/webapp/pull/56. In a related move I added tests around the search endpoint autocomplete uses.
The new `search` action tests uncovered an issue where a request with no parameters would return all finishers. The current HTML form only makes requests with three or more characters so this would be an unexpected state. Rather than ignore it I felt like it was better to explicitly handle the case.
> Add tests for manage finishers and projects controllers

- .overcommit.yml
- test/test_helper.rb
There have been a few issues with warnings or hanging while running tests. Overcommit also had errors as it assumed RSpec by default. This branch:
* Turns on `minitest` in Overcommit `PrePush`
* Add the `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=ON` env to Overcommit, too
* Removes the test parallelization that creates flakey Rails tests (we don't have that many tests)
* Note: One of the tools also reformatted a stub but there is no substantive change
> Fix a few automated test issues

- .annotaterb.yml
- Gemfile
- Gemfile.lock
- app/models/assessment.rb
- app/models/assignment.rb
- app/models/assignment_update.rb
- app/models/favorite.rb
- app/models/finisher.rb
- app/models/product.rb
- app/models/project.rb
- app/models/project_note.rb
- app/models/skill.rb
- app/models/user.rb
- lib/tasks/annotate_rb.rake
- test/fixtures/assessments.yml
- test/fixtures/finishers.yml
- test/fixtures/projects.yml
- test/fixtures/skills.yml
- test/fixtures/users.yml
- test/models/finisher_test.rb
- test/models/project_test.rb
For easy access rake db:migrate now annotates models with the content of the database table they are associated with.
> Annotate Models with Database columns automatically

- app/controllers/manage/projects_controller.rb
- app/models/assignment.rb
- app/models/project_note.rb
- app/views/manage/projects/index.html.haml
- app/views/manage/projects/show.html.haml
- test/controllers/manage/projects_controller_test.rb
- test/fixtures/projects.yml
- test/models/project_test.rb
- test/test_helper.rb
Each Project should have a date field labeled 'Last update'. Any time something changes within the project, the date should automatically update.
When using search, the date field should be able to be used for searching and sorting. I.e. the user should be able to search for projects with a last update that falls in a date range (e.g. before November 1st) and should be able to sort any search results by date of last update.
- add `touch: true` to both `project_notes` and `assignments` so when either of those associations get changed in any way, the parent project's `updated_at` timestamp is updated. `updated_at` will still be updated if the project itself has any changes too
- update the project search/filter page to be able to filter by `updated_at`. I moved things around a little bit to …
> Add ability to filter projects by last updated

- Gemfile
- Gemfile.lock
Silence warnings about ruby 3.4.X
- drb
- csv
- mutex_m
```bash
warning: /root/.asdf/installs/ruby/3.3.7/lib/ruby/3.3.0/mutex_m.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add mutex_m to your Gemfile or gemspec to silence this warning.
warning: /root/.asdf/installs/ruby/3.3.7/lib/ruby/3.3.0/drb.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add drb to your Gemfile or gemspec to silence this warning.
Also please contact the author of activesupport-7.0.8.7 to request adding drb into its gemspec.
```
> Include required gems that are being removed from ruby 3.4.0

- Gemfile.lock
- bin/bundle
Apparently rubocop updated bundle/bin and that is now breaking on heroku.  Reverting the change, see [here](https://stackoverflow.com/questions/67910193/heroku-bundler-undefined-method-present-fails-to-install-gems-via-bundler)
> Fixing bundle/bin

- app/models/assignment.rb
- app/views/manage/assignments/_assignment_form.html.haml
- test/controllers/manage/assignments_controller_test.rb
- test/models/assignment_test.rb
After deploying #100 there were a few issues managing projects. The root of this is that my original change did not take into account existing Assignment objects which would have a `nil` status. To fix this I changed `allow_nil` to `allow_blank` and added a `before_save` to normalize to `nil`. This means that the "Unknown" option in the form drop down (which sends an empty string) is now a valid option. This allows saving of existing records with no status or purposely choosing "Unknown". I've added model and controller tests to verify this.
A small visual issue was also fixed. The Assignment form was using the `Assignment#updated_at` and an arbitrary 5 second window to display the "SAVED" label. This meant that right after creation, or on page refresh soon after a change, it would be …
> Assignment status validation follow ups

- app/views/manage/assignments/_assignment_form.html.haml
- app/views/manage/projects/_form.html.haml
- app/views/manage/projects/show.html.haml
- app/views/projects/_crafter_form.html.haml
- app/views/projects/_details.html.haml
- app/views/projects/edit_crafter.html.haml
- app/views/projects/show.html.haml
Change the UI from "crafter" to "original crafter" for clarity. This was part of a [few requested copy changes](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec08G9DKUZPB), most of which were completed in #145. I also fixed a second [copy update](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec08FYB13N14) for "Finisher Status". While reviewing I noticed that sections with no data were laid out oddly so I added a "Not Provided" message to those sections:
> Minor copy changes for crafter and finisher

- Procfile
- config/puma.rb
Prevent me from [botching a deploy](https://looseendsproject.slack.com/archives/C05GUDK4620/p1741020997610329?thread_ts=1741018894.587149&cid=C05GUDK4620) by missing a `rake db:migrate`. This PR adds a `Procfile` that defines a [Heroku Release Phase](https://devcenter.heroku.com/articles/release-phase) with the `rake db:migrate` command. This will run the migration before the Dyno restarts to make sure that all Rails startups see the new database changes. While setting up the `Procfile` I also took [Heroku's recommendation to turn on Puma](https://devcenter.heroku.com/articles/ruby-default-web-server). A Puma configuration mostly existed with the small addition of `preload_app!`, which I've found in past projects stops the first few requests from being slow after a deploy or restart.
I …
> Automatically run db:migrate on deploy

- .rubocop.yml
- Gemfile
- Gemfile.lock
- Correcting `rubocop.yml` file to have plugins block for supported gems.
- Added `rubocop-performance` for best practices around ruby code performance
> Rubocop formatting updates for plugins

- config/storage.yml
- scripts/one_time/migrate_attachments.rb
Aaaargh.  After hours of myself and @swards fighting with AWS CLI to copy S3 objects from one account to another, I learned that that was the wrong approach.  So this is the right approach.
> Blob migration script

- app/views/manage/projects/show.html.haml
- Render image whenever there is a pattern.
- Open all images in new tab
Old:
New:
> Render pattern detail images in admin pages

- app/assets/stylesheets/application.sass
- app/controllers/manage/projects_controller.rb
- app/models/project.rb
- app/views/layouts/_address_form.html.haml
- app/views/manage/projects/_form.html.haml
- app/views/manage/projects/show.html.haml
- db/migrate/20250312164001_add_material_brand_to_projects.rb
- db/schema.rb
- test/controllers/manage/projects_controller_test.rb
- test/controllers/projects_controller_test.rb
- test/fixtures/projects.yml
- test/models/project_test.rb
Add "Material Brand" attribute to `Project` as `material_brand`. The  [Slack list item](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec08G364C8BF) had a few requirements:
1. Only displayed and editable in the manager view
2. Should be searchable
While I was adding this I also cleaned up the form display on narrower viewports as that's often how I side-by-side test.
> Add Material Brand to Project

- app/views/application/_navigation.html.haml
- app/views/layouts/admin.html.haml
- app/views/layouts/application.html.haml
- app/views/layouts/mailer.html.haml
- app/views/layouts/manage.html.haml
- app/views/projects/_basics_form.html.haml
- app/views/projects/_project_form_fields.html.haml
- app/views/projects/_publicity_form_fields.html.haml
- app/views/projects/_submitter_form_fields.html.haml
- test/controllers/projects_controller_test.rb
I was gonna pick up the tickets to add Original Crafter details as required fields to the project submission form.
But I found myself doing a lot of reorganizing and I didn't want my PR to bloat too much.
This PR doesn't make any logic changes. It uses [Julie's designs](https://www.figma.com/design/X09cMIMc6r5j0T5dSimrLv/Loose-Ends-Project?node-id=66-6484&t=lXPenDr5MYomjyNb-1) as a reference 
- Some small accessibility fixes 
- HTML lang attrs
- image alt for the main nav logo 
- correctly associate labels with their inputs for screen readers and keyboard nav
- Separate the project submission form into a couple partials 
- I'd like to use these in subsequent PRs to reorganize the edit project screens to more closely match the new sections/organization
- Make necessary inputs required on …
> Project submission UI updates

- app/controllers/manage/project_notes_controller.rb
- app/models/assignment.rb
- app/views/manage/project_notes/_form.html.haml
- app/views/manage/projects/_project_card.html.haml
- app/views/manage/projects/_project_row.html.haml
- app/views/manage/projects/show.html.haml
- config/initializers/blob_overrides.rb
- db/migrate/20250320170812_add_last_contacted_at_to_assignment.rb
- db/schema.rb
- test/controllers/manage/project_notes_controller_test.rb
- test/fixtures/assignments.yml
- test/models/assignment_test.rb
Add the ability to store the last contact date for an assignment. This will be used to track when the last time a finisher was contacted about a project. Also included here is a checkbox to update the date when adding a project note.
This data may be populated by the auto CC'd emails in the future. At that time we can update this field when the email arrives. I might have held off on this change until email work is completed but it has a few longer term benefits:
1. Decouples this date tracking from the email work so nobody is blocked (since this was easy)
2. Updating this at email time will reduce the load of the project management pages since the denormalized value won't require joining to the email date records.
3. This checkbox will give the manager a way to update if there are out of …
> Add last contact date to Assignment

- app/models/project.rb
- app/views/manage/projects/index.csv.haml
- test/controllers/manage/projects_controller_test.rb
When exporting projects to a CSV, the resulting file should include the project owner's contact information: email and phone number
> Add owner contact info to project csv

- app/views/application/_submitter_form_fields.html.haml
- app/views/layouts/_address_form.html.haml
- app/views/manage/projects/_form.html.haml
- app/views/projects/_address_form.html.haml
- app/views/projects/edit_project.html.haml
- app/views/projects/show.html.haml
This is the last bit required to get the "submit project" form all in a single form instead of requiring additional info after submission.
- update address layout to match new 2 col ui
- in the finishers manage UI, the spacing on this form doesn't match existing spacing but I think that's fine. We're incrementally getting the UI ironed out. 
- add address fields to project submitter form fields
- update project show UI to be slightly cleaner
> Update mailing address form styling and include in project submitter details

- config/initializers/blob_overrides.rb
- config/storage.yml
If a developer is using live data in their local db and does not have the live AWS credentials in their .env, they'll get 500s on everything because `representable?` (as modified) tries to reach out to the `active_storage_blobs.service_name` storage service to make sure the object exists before trying to download it.  This mod handles that case.
> Handle overridden ActiveStorage::Blob.representable? for certain dev environments

- app/views/manage/projects/show.html.haml
Adding warning when project address is incomplete preventing the mapping function from being used.
Old:
New:
> Adding warning when missing address

- app/assets/stylesheets/application.sass
- app/views/manage/assignments/_assignment.html.haml
- app/views/manage/assignments/_assignment_form.html.haml
- app/views/manage/finishers/show.html.haml
- app/views/manage/projects/_project_card.html.haml
- app/views/manage/projects/_project_row.html.haml
- app/views/manage/projects/index.html.haml
- app/views/manage/projects/show.html.haml
- test/controllers/manage/assignments_controller_test.rb
There were a few small items related to project display I bundled up into a single PR:
1. Project list: [Rename 'Last Contacted' to 'Last Finisher Response'](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec08LCC527GQ)
2. Project list/card: [Remove 'Last Updated'](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec08LMTYJWCQ)
3. [Add Finisher email to assignment card](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec08KN37S3DK)
4. [Assignment card on Finisher page should link to Project instead of Finisher](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec08KHRWE0G6)
Reformatted for clarity. Made link at top contextual. Showing side by side of the card from Project page (left) …
> Collection of data clarity issue in project display

- app/models/concerns/loose_ends_searchable.rb
- app/models/project.rb
- test/controllers/manage/projects_controller_test.rb
Add a new Project status of "test". These are excluded from the Project search/list page unless you specifically search for status=test. This should accomplish to goal of [hiding the distracting test projects](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec08KA3SN7TR) while letting integration work continue. If we fell they are still a distraction or a problem we can revisit adding a Project delete function.
> Add Project Status Test (hidden by default)

- app/views/manage/projects/_project_row.html.haml
Per a Slack request from Jen the finisher email is much more helpful than the name in the contact of Project search list views:
> Display email instead of name for project list view

- app/assets/stylesheets/application.sass
- app/javascript/controllers/clipboard_controller.js
- app/javascript/controllers/index.js
- app/views/manage/finishers/show.html.haml
- app/views/messages/_index.html.haml
This is one of the things reusable Stimulus controllers are really good at so I used that. The Stimulus frameworky bits will handle hooking this up to the page elements during load or `turbo:load` as needed. The crux is that any element with `data-controller="clipboard"` will get the little clipboard icon appended and support click-to-copy with the associated feedback (see below).
I convert one existing copy to clipboard use and added a new one for finisher profile email addresses. This feels like a feature managers will want in more places once it's available.
> Add a reusable copy-to-clipboard component

- app/views/manage/projects/show.html.haml
Craft type now appears on project overview page - no longer need to go into edit mode to view craft type
Improvement item: [Make the craft field visible on the project page (when not in edit mode)](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec08MJBVSGQG)
Screenshot:
> Add craft type to project overview

- app/controllers/application_controller.rb
- app/controllers/finishers_controller.rb
- app/controllers/projects_controller.rb
- app/views/manage/projects/show.html.haml
- test/integration/user_access_test.rb
Fix an issue with PDF pattern files. This change uses `file.variable?` to guard attempting to generate a variant URL. If the file cannot generate a variant (like a PDF) we show the file name instead.
Also fixed here was an issue where logins with a return path set in the Devise cookie were throwing a 500. There was a logic flaw in `&& return` causing a nil return value. A unit test was added to confirm. The `before_filter` used to set return paths needed to be prepended to return before authentication in the test.
Fixes: [Can't transform blob with ID=? and content_type=application/pdf](https://heroku-cfc27630.airbrake.io/projects/519044/groups/4049059313744366905?tab=overview)
Fixes: [ ActionController::ActionControllerError:  Cannot redirect to nil! …
> Hotfix: PDF pattern files + login redirect

- app/controllers/application_controller.rb
- app/controllers/finishers_controller.rb
- app/controllers/projects_controller.rb
- app/views/manage/projects/show.html.haml
- test/integration/user_access_test.rb
Fix an issue with PDF pattern files. This change uses file.variable? to guard attempting to generate a variant URL. If the file cannot generate a variant (like a PDF) we show the file name instead.
Also fixed here was an issue where logins with a return path set in the Devise cookie were throwing a 500. There was a logic flaw in "&& return" causing a nil return value. A unit test was added to confirm. The before_filter used to set return paths needed to be prepended to return before authentication in the test.
> Hotfix: PDF pattern files + login redirect (#340)

- app/mailboxes/forwards_mailbox.rb
- lib/tasks/backfill.rake
- lib/tasks/email.rake
- test/fixtures/finishers.yml
- test/fixtures/projects.yml
- test/mailboxes/forwards_mailbox_test.rb
Two email fixes:
- handle downcase and mixed case inbound_email_addresses
- handle where inbound_email_address is not first in the to: array
- rake task to reprocess failed InboundEmails
> HOTFIX InboundEmails

- app/views/manage/assignments/new.html.haml
- app/views/projects/_crafter_form_fields.html.haml
This fixes a couple of template errors reported in Airbrake:
1. [ActionView::Template::Error:  Cannot get a signed_id for a new record](https://heroku-cfc27630.airbrake.io/projects/519044/groups/4050722068062817633?tab=overview). This was an error showing the Project creating page after a create failed to validate (edge case). I added a `variable?` check to the display so we don't call `image.representation` when it cannot succeed.
2. [ActionView::Template::Error: undefined method name for nil](https://heroku-cfc27630.airbrake.io/projects/519044/groups/4051258116673129858?tab=overview). This calls `finisher.name` instead of `finisher.user.name` though when I checked the Finisher, Project, and User all exist. I doubt this fixes it but it narrows it down f it happens again.
> Correct a couple of Airbrake template errors

- app/assets/stylesheets/application.sass
- app/controllers/manage/projects_controller.rb
- app/models/assignment.rb
- app/models/concerns/loose_ends_searchable.rb
- app/models/project.rb
- app/views/manage/assignment_updates/_assignment_update.html.haml
- app/views/manage/assignment_updates/create.html.haml
- app/views/manage/assignment_updates/destroy.html.haml
- app/views/manage/assignment_updates/new.html.haml
- app/views/manage/assignments/_assignment_form.html.haml
- app/views/manage/assignments/_form.html.haml
- app/views/manage/dashboards/show.html.haml
- app/views/manage/projects/_form.html.haml
- app/views/manage/projects/_project_card.html.haml
- app/views/manage/projects/_project_status_form.html.haml
- app/views/manage/projects/_search.html.haml
- app/views/manage/projects/_status.html.haml
- app/views/manage/projects/index.html.haml
- app/views/manage/projects/show.html.haml
- app/views/manage/projects/update.turbo_stream.haml
- db/migrate/20250418183845_update_default_status.rb
- db/migrate/20250422115749_change_default_status.rb
- db/schema.rb
- lib/tasks/backfill.rake
- test/controllers/manage/projects_controller_test.rb
- test/fixtures/projects.yml
- test/jobs/send_check_ins_job_test.rb
- test/models/assignment_test.rb
- test/models/project_test.rb
We had three status columns on Project:  `status`, `ready_status`, and `in_process_status`, with the latter two being substatuses.  It complicated the UI and managers weren't consistent about using substatuses.  So, this PR flattens the status list (packs any necessary substatuses into the string), simplifies the UI, and migrates old values into new ones through `rake backfill:convert_project_status`.  It also updates `Assignment.needs_check_in` to consider project status in addition to Assignment status.  This is the new list
```
STATUSES = [
"PROPOSED",
"WAITING PROJECT CONFIRMATION",
"READY TO MATCH: NEW",
"READY TO MATCH: ADDITIONAL ATTEMPT",
"READY TO MATCH: NEEDS SECOND SKILL",
"READY TO MATCH: REMATCH REQUESTED",
"FINISHER INVITED",
"ACCEPTED WAITING TERMS",
"INTRODUCED",
"IN …
```
> Simplify Project status

- app/assets/stylesheets/application.sass
- app/javascript/controllers/clipboard_controller.js
There were some reports in Slack of the copy to clipboard utility not working correctly. I could not reproduce them but in at least one case someone mentioned refreshing solved it. I did a few different things to make it more robust:
1. Use the Promise returned by `navigator.clipboard.writeText` to catch errors. In this case copy is disabled so the user can select the text the old fashioned way.
2. Do not copy-on-click when showing the copy confirmation. That way a double-click does not copy the text "Coped!"
3. Cleanup some duplicated strings
> Make clipboard copy untility more robust

- app/assets/stylesheets/animations.sass
- app/assets/stylesheets/application.sass
- app/views/manage/_update_label.html.haml
- app/views/manage/assignments/_assignment_form.html.haml
- app/views/manage/projects/_needs_attention_form.html.haml
- app/views/manage/projects/_project_status_form.html.haml
As a follow up to some discussion on #353 I looked at making the temporary "SAVED" label component more reusable. I was going to following something like #302 but when I thought it through it turned out Stimulus was overkill. I was able to simplify this to not use Javascript at all. This now uses a CSS animation and delay so any properly formed markup Just Works™. Since the markup needs are a little specific I moved that into a partial as well to make it easy to use.
> Make the "SAVED" label on Turbo updates simpler

- app/models/message.rb
- app/views/projects/_crafter_form_fields.html.haml
- test/controllers/projects_controller_test.rb
- test/models/message_test.rb
- Temporarily disable auto-update of assignments.last_contacted_at triggered by inbound emails
- Fix crafter image template errors on validation failure
> HOTFIXES post 2025-04-24 release

- app/views/manage/projects/_project_row.html.haml
- app/views/manage/projects/index.html.haml
While testing the new links+copy added in #365 on staging I ran into an error. If the link was followed, and then the back button used, a browser console warning was thrown and both column sort and copy stopped working. The root cause is something with how Turbolinks is reloading pages. Since the speed of these requests is fast I disabled the Turbo loading in this case so it works correctly while I research other solutions.
> Fix copy/paste bug and browser console warning

- app/assets/stylesheets/application.sass
- app/controllers/manage/finishers_controller.rb
- app/controllers/manage/reports_controller.rb
- app/controllers/users/sessions_controller.rb
- app/models/finisher.rb
- app/models/user.rb
- app/views/manage/dashboards/show.html.haml
- app/views/manage/finishers/_finisher_card.html.haml
- app/views/manage/finishers/_finisher_row.html.haml
- app/views/manage/finishers/_form.html.haml
- app/views/manage/finishers/map.html.haml
- app/views/manage/finishers/show.html.haml
- app/views/manage/job_logs/_compact.html.haml
- app/views/manage/notes/_compact.html.haml
- app/views/messages/_compact.html.haml
- app/views/messages/_index.html.haml
- app/views/messages/show.html.haml
- config/initializers/time_formats.rb
- config/storage.yml
- lib/tasks/dev.rake
- test/controllers/manage/finishers_controller_test.rb
- test/controllers/users/sessions_controller_test.rb
* Sort messages created_at desc on project/show
* Show email confirmation status, allow update on Finisher edit
* Confirm email on magic link click
* Remove deprecated constant
* Change :compact time format (%e?  what's the point if it inserts a space?)
* Rake task to copy email blobs for dev
* Clean up message/show for emails
* Standardize date display on dashboard
> Expose confirmed/unconfirmed email addresses (#373)

- app/views/manage/projects/show/_row_images.html.haml
I found a project in my dev environment throwing an error if there was a PDF where an image was expected. Since `ActiveStorage` has content types I just added check. In the refactor in #389 the image display all runs through the same partial so it was a small fix.
> Guard against PDFs in images by checking content type

- app/jobs/send_check_ins_job.rb
- app/models/assignment.rb
- app/models/project.rb
- config/recurring.yml
- test/controllers/manage/projects_controller_test.rb
- test/jobs/send_check_ins_job_test.rb
- test/models/assignment_test.rb
- test/models/project_test.rb
For Assignments in "Accepted" status with Projects in "IN PROCESS: UNDERWAY" status that have at least four check-in messages sent to the Finisher with no responses, the system will not send a fifth check-in (after 8 weeks), but will mark the Assignment "Unresponsive" status and the Project needs attention reason will be "Finisher Unresponsive".
> Escalate Project into "Needs Attention" after four check ins

- app/models/concerns/loose_ends_searchable.rb
- app/views/manage/projects/show.html.haml
- app/views/manage/projects/show/_details.html.haml
- app/views/manage/projects/show/_notes.html.haml
- test/controllers/manage/projects_controller_test.rb
It turns out #389 was just too big and created some fallout. This follow up fixes the issues reported after deploy:
1. Duplicate project search results: The change from `joins` to `left_outer_joins` to handle Projects with _no_ assignments better ended up causing one result per assignment if there were multiple. I fixed this using `.distinct` but because of the sorting logic it was a little more complex (see `loose_ends_searchable.rb`) 
* This had good tests that helped my catch the complexity 🙌 
3. Reorder the project detail sections to move attributes to the bottom
4. Add `project_images`: I somehow in double checking for missing items during #389 I think misread `pattern_files` as but itself _and_ `project_images`
5. Remove duplicate project phone number display (where `project_images` …
> Project Details Redesign Followup

- app/javascript/application.js
I broke this in #387 when I found two versions of Bootstrap JS. It turns out our bundled Bootstrap included it already and we were loading it. I removed the extra load without finding the error it created. This change makes `window.bootstrap` (aka `bootstrap`) available via JS throughout the site instead of only within JS modules. This will fix the popovers not working when viewing finisher notes on the manager dashboard.
> Make bootstrap available in JS to fix issues with Popover use

- app/controllers/manage/projects_controller.rb
- app/views/manage/projects/index.html.haml
- test/controllers/manage/projects_controller_test.rb
Make the "Last Finisher Response" field on the project search list view sortable. This was the only column not yet searchable because it required a more complex query. I sorted out the join/max query in the PR and added it.
See Also: [Slack list item](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec08NA0J48N6)
> Allow project search sort by last_contacted_at

- app/controllers/assignments_controller.rb
- app/models/assignment.rb
- app/models/note.rb
- app/views/assignments/check_in.html.haml
- test/application_system_test_case.rb
- test/controllers/assignments_controller_test.rb
- test/jobs/send_check_ins_job_test.rb
- test/models/assignment_test.rb
- test/models/note_test.rb
Check-in form allowed null Note params.  A null `sentiment` on a Note of `notable_type == "Assignmment"` breaks views.  Also added a validation that a Note of sentiment "need_help" (negative response) requires a :text param.
> Validate Note on Finisher check-in response

- app/models/assignment.rb
- test/models/assignment_test.rb
`assignment.last_contacted_at` starts out nil.  The logic in `Assignment#missed_check_ins?` did not take this into account, breaking SendCheckInsJob
> Handle nil last_contacted_at in Assignment#missed_check_ins?

- app/controllers/assignments_controller.rb
- app/models/note.rb
- app/models/project.rb
- app/views/assignments/check_in.html.haml
- test/controllers/assignments_controller_test.rb
- test/models/project_test.rb
Per [this request in Slack](https://looseendsproject.slack.com/archives/C066WSK1X46/p1748439137873289):
> We need to add DONE as an option in the auto generated check-in email. Right now people can only choose GOING WELL, NO PROGRESS, or NEED HELP. I've had folks mark GOING WELL and in the notes say they are done with the project.
This adds the status as `completed` to be clear the intent. The change was pretty minor but required some changes to Project#needs_attention as well. I added tests to go along with this. With four options the page was getting tight to I widened the content area a bit, like so:
> Add 'completed' option to finisher checkins

- app/views/application/_project_form_fields.html.haml
Description:
The helper text of "What type of craft?" currently reads "Knit, Crochet, Quilt. If you do not know, say "I don't know."" There should be an "etc" in the list so that people don't think it has to be one of those three. It should be updated to read "Knit, Crochet, Quilt, etc. If you do not know, say "I don't know.""
Before:
After:
> Add "etc" to description of craft options

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .github/workflows/.tests.yml
- Gemfile
- Gemfile.lock
- test/application_system_test_case.rb
- test/controllers/manage/inbound_emails_controller_test.rb
- test/test_helper.rb
Capybara tries to run as part of `overcommit`. However, there was no container or installed copy of chrome for it to connect to and run tests with. 
This is problematic for local development while running in a DevContainer. 
This PR attempts to correct that issue to allow for `overcommit` to run `rspec` and `minitests` prior to commit.
> Capybara Local Runner Configuration for Dev Container

- app/models/finisher.rb
- app/views/finishers/_favorites_form.html.haml
A finisher can already optionally add photos of their work to their profile.
There should be a maximum of 5 pictures. There should be a short description saying "(Optional) Add up to 5 photos of your work. This helps us match the right projects to the right people."
This PR adds an ActiveRecord validation on the number of files for a finisher's `finished_projects`. It also adds a check that the image is persisted before trying to render it's little thumbnail to prevent a 500 when the `finished_projects` field throws a validation error before successfully saving.
> Limit the amount of photos a finisher can upload

- app/models/finisher.rb
- test/controllers/finishers_controller_test.rb
- test/controllers/manage/finishers_controller_test.rb
- test/models/finisher_test.rb
> Couple of weird errors today. I keep getting an error (Unprocessable Entity) when I try to go into this person's record. https://app.looseendsproject.org/manage/finishers/103998 it happened yesterday and today. And this person https://app.looseendsproject.org/manage/finishers/109265 when I go to update it says Finished Projects files exceed limit, but when I try to delete one, it gives me an error (Not Found).
from [Slack](https://looseendsproject.slack.com/archives/C066WSK1X46/p1750944896243679)
It turns out the validation added in #464 was triggering an error on the `manage/finisher/:id` show action. This is because #239 added some backfill that calls `save!` on a Finisher during show. I suspect the delete is also running into an issue where there is one fewer but still too many.
This …
> Only validate finished_projects if it is updated.

- app/controllers/manage/finishers_controller.rb
- app/models/concerns/loose_ends_searchable.rb
- app/views/manage/projects/show/_crafter.html.haml
- test/controllers/manage/projects_controller_test.rb
The `can_share_crafter_details` field was showing in the Project edit view but not the read-only view. This PR adds that. It also fixes a query issue causing [a 500 error](https://looseendsproject.slack.com/archives/C08BY414BED/p1750710202197799) when clicking on some column headers in the project and finisher searches.
> Surface can_share_crafter_details in Project manage

- app/mailers/finisher_mailer.rb
- test/mailers/finisher_mailer_test.rb
When sending check in emails set the `Reply-To` header to the manager. This does not really send emails _from_ the manager, but anyone hitting **reply** will end up emailing the manager instead of `info@`. I went ahead and did this now so it's a handy example for the upcoming ["Project offer" email](https://looseendsproject.slack.com/archives/C05GUDK4620/p1752861130090349).
> Send project checkin emails 'from' manager

- app/views/manage/projects/_search_v2.html.haml
- test/controllers/manage/projects_controller_test.rb
> Click on a saved search: Not Found The page you were looking for doesn’t exist. You may have mistyped the address or the page may have moved. If you’re the application owner check the logs for more information.
[Slack](https://looseendsproject.slack.com/archives/C05GUDK4620/p1754596906316859)
It turns out the URL for the saved search should be `?load_view=id` but was `load_view=id` (no `?`). I added that as well as a test.
> Fix broken link for saved searches

- app/controllers/manage/projects_controller.rb
- test/controllers/manage/projects_controller_test.rb
Any saved search with a country or project status in the filters was not saving correctly. The root cause as a `permit` call with incomplete parameters. That was caused by saving these in an array when `permit` takes a more complex argument to allow for the description of array params, which we use for statuses. I added controller tests to verify this will continue to work.
> Fix issue with saved searches not saving

- app/models/project.rb
- test/models/project_test.rb
Assignment `last_contacted_at` starts out as nil.  If a Finisher ignores every check-in email (or doesn't receive them), the Assignment will never be escalated to Needs Attention -> Finisher Unresponsive.  This PR adds an after_save callback on Project to set last_contacted_at on all of that Project's accepted assignments with nil last_contacted_at times.
> Project after_save callback to set assignment last_contacted_at
