looseendsproject/webapp

DEVELOPERS.md

Adding my name to DEVELOPERS.md file for my first pull request.

Add name to DEVELOPERS.md

---

app/controllers/admin/skills_controller.rb
app/models/finisher.rb
app/models/skill.rb
app/views/admin/skills/_form.html.haml
app/views/admin/skills/_skill.html.haml
app/views/admin/skills/index.html.haml
db/migrate/20231210033135_add_position_to_skills.rb
db/schema.rb

This adds a position column and now sorts assessments and skills by skills.position
Now sorting by default on the profile pages, I think.

SC-69: Sorting skills by position

---

app/views/finishers/_profile_form.html.haml

Added div.form-info that indicates user gives implied consent by providing phone number and submitting form per wording provided by Masey.

Add .form-info noting implied consent to phone number section of form.

---

README.md
app/controllers/admin/users_controller.rb
app/views/admin/users/show.html.haml
config/routes.rb

This allows Admins to login as another user and see what they see.
Routes updated, must be an Admin

Assume Identity for Admins

---

app/controllers/admin/products_controller.rb
app/controllers/admin/skills_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/finishers_controller.rb
app/controllers/manage/assignments_controller.rb
app/controllers/manage/finishers_controller.rb
app/controllers/manage/projects_controller.rb
app/controllers/projects_controller.rb
app/views/layouts/admin.html.haml
app/views/layouts/application.html.haml

This PR adds and updates title tags to make them more descriptive so browser history can be used more effectively.
Example browser history after navigating through the Finisher Profile, Manage, and Admin sections of the app:

Use more descriptive browser titles

---

app/views/home/show.html.haml

The blurb above the "Submit your project" button needs to be updated to read:
> Once Loose Ends receives your project submission, we will look through our database of finishers to find a good match. With considerations to geography, craft, skill level, and preferences, we will identify a good fit based on the information volunteer finishers submitted in their profiles.
> 
> After we identify a good finisher for you, we will offer them details about your project and wait for their reply. Once they agree to the job, we will introduce you in an email. Thanks for trusting Loose Ends with your precious handwork. We'll be in touch soon.
Before:
After:

Update blurb above Submit your project button

---

.gitignore
DEVELOPERS.md
Gemfile.lock
README.md
config/boot.rb

Found some voodoo here.  Didn't want to mess w/ concurrent-ruby
https://stackoverflow.com/questions/79360526/uninitialized-constant-activesupportloggerthreadsafelevellogger-nameerror

More setup steps

---

app/controllers/manage/projects_controller.rb
app/views/manage/projects/_search.html.haml
test/controllers/manage/projects_controller_test.rb

Changing the default sort for Projects

Default project sort

---

app/assets/stylesheets/application.sass
app/controllers/manage/finishers_controller.rb
app/models/finisher.rb
app/views/manage/finishers/_finisher_card.html.haml
app/views/manage/finishers/show.html.haml
app/views/manage/projects/show.html.haml

They now show up with a red and pink border so Jen sees them in search

Initial treatment for assigned finisher card

---

app/helpers/application_helper.rb
app/mailers/devise_mailer.rb
app/models/user.rb
app/views/layouts/admin.html.haml
app/views/layouts/mailer.html.haml
app/views/layouts/manage.html.haml
app/views/manage/dashboards/show.html.haml
config/initializers/override_staging_recipient.rb
db/schema.rb
test/fixtures/products.yml
test/fixtures/users.yml

- show mail template previews on manage/dashboard
- redirect staging emails to test account (for email client format validation)

Mailers #2:  mail template previews; redirect staging emails to test account

---

test/controllers/manage/projects_controller_test.rb

Followup to PR #137 which added search. Now that it has been deployed and the general functionality has been confirmed I've come back to add some basic tests. This tests the new plain text search field and the other parametric search options that existed already since they were refactored.

Add project search tests

---

app/controllers/manage/finishers_controller.rb
app/controllers/manage/projects_controller.rb
app/models/project.rb
app/views/manage/finishers/index.csv.haml
app/views/manage/finishers/map.html.haml
app/views/manage/projects/_project_card.html.haml
app/views/manage/projects/_search.html.haml
app/views/manage/projects/index.csv.haml
config/routes.rb
test/controllers/manage/finishers_controller_test.rb
test/controllers/manage/projects_controller_test.rb

This PR contains three closely related changes. 
1. a small request to [add country to the existing finishers export](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec07U89G0WMD).
2. a follow up request from #137 to [provide a similar CSV export for project searches](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F08B7PGPUMU?record_id=Rec08F5NZJMB8).
3. a request for a [csv export on the finisher map view](https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec07DPB3SZHB)

CSV Export Improvements

---

app/views/application/_navigation.html.haml

- Change from Settings to User Name
- Add hover effect to navigation links

Navigation hover effect and title bar alteration

---

app/views/projects/_address_form.html.haml
app/views/projects/edit_address.html.haml

Change the title of the Mailing address page

---

app/views/active_storage/blobs/_blob.html.haml
app/views/finishers/_favorites_form.html.haml
app/views/finishers/show.html.haml
app/views/manage/projects/_form.html.haml
app/views/manage/projects/show.html.haml

When you are an admin editing a project, the button now says Save
https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec08GN0PGU3S

Allow for conditional button on edit project page

---

app/controllers/manage/finishers_controller.rb
app/controllers/manage/projects_controller.rb
app/models/project.rb
app/views/manage/finishers/index.csv.haml
app/views/manage/finishers/map.html.haml
app/views/manage/projects/_project_card.html.haml
app/views/manage/projects/_search.html.haml
app/views/manage/projects/index.csv.haml
config/routes.rb
test/controllers/manage/finishers_controller_test.rb
test/controllers/manage/projects_controller_test.rb

Resubmitting #148 so I can merge to `main` this time instead of `staging`. I misunderstood the deploy branch discussion and merged to `staging` instead and it was overwritten.

CSV export re-submit

---

app/views/manage/projects/_form.html.haml

https://looseendsproject.slack.com/lists/T05GP1TRWQM/F07E2EA51B2?record_id=Rec08G3AWV10V

Add Cancel button to project edit form

---

lib/tasks/blobs.rake

Chunk up the enqueuing so as not to crash the Heroku dyno...

Make the rake task not crash the dyno

---

app/views/home/_card_finisher.html.haml

Minor landing/home page copy change

Change Ravely link to Bluesky

---

app/views/manage/projects/_project_row.html.haml
app/views/manage/projects/index.html.haml

There are three small updates to be made in the project list view:
- Remove location
- Change "Owner" to "Project Owner"
- Show the Project Owner's email instead of their name

Update project list view

---

app/models/concerns/loose_ends_searchable.rb

Hotfix for searchable#with_sub_status

---

app/controllers/projects_controller.rb
app/javascript/controllers/hello_controller.js
app/javascript/controllers/index.js
app/javascript/controllers/select_controller.js
app/models/project.rb
app/views/application/_project_form_fields.html.haml
db/migrate/20250310040636_require_images_if_available.rb
db/schema.rb
test/fixtures/projects.yml
test/models/project_test.rb

if user selects 'yes' to 'materials available?' or 'is there a pattern?' then the corresponding image/file upload becomes required
[Screencast from 2025-04-14 14-17-18.webm](https://github.com/user-attachments/assets/05632e07-698b-4be0-8be7-f65fbd806aab)

Make material images and pattern files required if available

---

.gitignore
app/controllers/manage/assignments_controller.rb
app/models/note.rb
app/views/manage/dashboards/_recent_notes.html.haml
app/views/manage/dashboards/show.html.haml
app/views/manage/notes/_compact.html.haml
db/grab_heroku_data.txt
test/controllers/manage/notes_controller_test.rb
test/fixtures/assignments.yml
test/fixtures/notes.yml
test/jobs/send_check_ins_job_test.rb
test/models/note_test.rb

Hold for any necessary hotfixes after prod release
- Note.for_assignment scope, tests, fixture

HOTFIXES 2025-04-17

---

.gitignore
app/controllers/manage/assignments_controller.rb
app/models/note.rb
app/views/manage/dashboards/_recent_notes.html.haml
app/views/manage/dashboards/show.html.haml
app/views/manage/notes/_compact.html.haml
db/grab_heroku_data.txt
test/controllers/manage/notes_controller_test.rb
test/fixtures/assignments.yml
test/fixtures/notes.yml
test/jobs/send_check_ins_job_test.rb
test/models/note_test.rb

* Instructions for grabbing prod data
* Note.for_assignment scope, fixtures, tests
* Fix Manage::AssignmentsController#create for "creator" not "user"

HOTFIXES 2025-04-17 (#335)

---

app/models/message.rb
lib/tasks/test.rake
test/controllers/manage/assignments_controller_test.rb
test/models/message_test.rb

* Test Manage::AssignmentsControllerTest#create
* Convenience rake task for statuses
* Only update assignment last_contacted_at if project in process

HOTFIX from 2025-04-17 release (#338)

---

app/controllers/manage/projects_controller.rb
test/controllers/manage/projects_controller_test.rb

:has_materials was not in the permitted params list.  Added test

HOTFIX Fix for has_materials not persisting

---

lib/tasks/backfill.rake

Logical spaghetti rendered inoperative by another change...

Fix bad rake task

---

app/views/manage/projects/_status.html.haml

- Show project status partial for managers

HOTFIX Show Manager project status partial

---

app/models/message.rb
test/models/message_test.rb

Now that emails are parsing correctly, we can safely update `Assignment.last_contacted_at` when a Finisher attaches an email to a Project.  The meat of it is `Message#update_last_contacted_at`.  Here's the logic:
```
def update_last_contacted_at
return unless messageable_type == "Project" && channel == "inbound"
user = User.find_by email: email_headers["from"].first
return unless user && user.finisher?
assignment = messageable.assignments.find { |a| a.finisher.user === user }
return unless assignment && assignment.project.status.match(/^in process/i)
assignment.update_attribute(:last_contacted_at, Time.zone.now) # rubocop:disable Rails/SkipsModelValidations
end
```
Human-readable logic is:  update the Assignment last_contacted_at if the Finisher is in the from: field AND the Project is …

Update last_contacted_at when Finisher sends an email

---

app/models/message.rb
test/models/message_test.rb

Update last_contacted_at when Finisher sends an email (#374)

---

app/models/assignment.rb

Small items for weekly release:
- Add Assignment status "requested rematch"

MISC items for 2025-05-08 release

---

app/models/project.rb
app/views/application/_project_form_fields.html.haml
app/views/manage/finishers/index.csv.haml
app/views/manage/projects/index.csv.haml
db/migrate/20250523002151_set_default_crafter_details.rb
db/schema.rb
test/application_system_test_case.rb
test/controllers/manage/assignments_controller_test.rb
test/controllers/manage/projects_controller_test.rb
test/fixtures/projects.yml
test/models/project_test.rb

Release for the week includes #406, #412, and #413

RELEASE 2025-06-05

---

.github/dependabot.yml
.github/workflows/.tests.yml
.gitignore

@SiobhanCoady sorry for the duplicate PR. I opened the other pr vs Main not Staging so it caused all kinds of hell.

Adding DependaBot auto merge and docker scanning

---

app/models/project.rb
app/views/projects/_crafter_form_fields.html.haml
db/migrate/20250612235841_add_dominant_hand_to_projects.rb
db/schema.rb
test/fixtures/projects.yml
test/models/project_test.rb

Adding Dominant Hand to the Projects Form

Adding Dominant hand field to projects
